application: gae-init
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- remote_api: on
- deferred: on
- appstats: on

inbound_services:
- warmup

libraries:
- name: jinja2
  version: latest

handlers:
- url: /favicon.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /p/(.*\.ttf)
  static_files: static/\1
  upload: static/(.*\.ttf)
  mime_type: font/ttf
  expiration: 1000d

- url: /p/
  static_dir: static/
  expiration: 1000d

- url: /.*
  script: main.app

skip_files:
- ^(.*/)?#.*#
- ^(.*/)?.*/RCS/.*
- ^(.*/)?.*\.bak$
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*~
- ^(.*/)?Icon\r
- ^(.*/)?\..*
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^lib/.*
- ^static/dst/.*
- ^static/ext/coffee/.*
- ^static/ext/css/.*
- ^static/ext/js/.*
- ^static/ext/less/.*
- ^static/src/.*
